// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbpcSPAqvOmLPgrEA3yO38xAM7-ikkx0',
    appId: '1:713217968202:web:c9de62e86678a05beffeb3',
    messagingSenderId: '713217968202',
    projectId: 'shifa-25809',
    authDomain: 'shifa-25809.firebaseapp.com',
    storageBucket: 'shifa-25809.firebasestorage.app',
    measurementId: 'G-T8S7LENGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1gr9secwnyL1fMZg1lzqno8vm_RLAb8',
    appId: '1:713217968202:android:8a09d526c4453878effeb3',
    messagingSenderId: '713217968202',
    projectId: 'shifa-25809',
    storageBucket: 'shifa-25809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXYm3JkJbgOSCs3ZI-RE5QSdYhhB8exA',
    appId: '1:713217968202:ios:bbcba115003366a0effeb3',
    messagingSenderId: '713217968202',
    projectId: 'shifa-25809',
    storageBucket: 'shifa-25809.firebasestorage.app',
    iosBundleId: 'com.example.shifa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXYm3JkJbgOSCs3ZI-RE5QSdYhhB8exA',
    appId: '1:713217968202:ios:bbcba115003366a0effeb3',
    messagingSenderId: '713217968202',
    projectId: 'shifa-25809',
    storageBucket: 'shifa-25809.firebasestorage.app',
    iosBundleId: 'com.example.shifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbpcSPAqvOmLPgrEA3yO38xAM7-ikkx0',
    appId: '1:713217968202:web:b3e55214ebc79ab3effeb3',
    messagingSenderId: '713217968202',
    projectId: 'shifa-25809',
    authDomain: 'shifa-25809.firebaseapp.com',
    storageBucket: 'shifa-25809.firebasestorage.app',
    measurementId: 'G-1BBRHKVK8L',
  );
}
