// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqzgt7250xi4g4AmSH368kJL_nif9na4g',
    appId: '1:14990694374:web:58485b2d61f5ea5a8a2827',
    messagingSenderId: '14990694374',
    projectId: 'shifaapp-f9163',
    authDomain: 'shifaapp-f9163.firebaseapp.com',
    storageBucket: 'shifaapp-f9163.firebasestorage.app',
    measurementId: 'G-YDZ15Q6F0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbGd0lbAZQoN_4wUFWoAdHmCkhlvKnpI',
    appId: '1:14990694374:android:a367b75be07a1aa58a2827',
    messagingSenderId: '14990694374',
    projectId: 'shifaapp-f9163',
    storageBucket: 'shifaapp-f9163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxzClaA3ZtrTvp_igg0wU1HHDAGuECXs',
    appId: '1:14990694374:ios:5a0439a3a15865ed8a2827',
    messagingSenderId: '14990694374',
    projectId: 'shifaapp-f9163',
    storageBucket: 'shifaapp-f9163.firebasestorage.app',
    iosBundleId: 'com.example.shifa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGxzClaA3ZtrTvp_igg0wU1HHDAGuECXs',
    appId: '1:14990694374:ios:5a0439a3a15865ed8a2827',
    messagingSenderId: '14990694374',
    projectId: 'shifaapp-f9163',
    storageBucket: 'shifaapp-f9163.firebasestorage.app',
    iosBundleId: 'com.example.shifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqzgt7250xi4g4AmSH368kJL_nif9na4g',
    appId: '1:14990694374:web:51a89ad70e3ce6478a2827',
    messagingSenderId: '14990694374',
    projectId: 'shifaapp-f9163',
    authDomain: 'shifaapp-f9163.firebaseapp.com',
    storageBucket: 'shifaapp-f9163.firebasestorage.app',
    measurementId: 'G-TZLWNCSH83',
  );
}
